### ISSUE TITLE
build_catkin_workspace.sh is specific to ros groovy only

### ISSUE THREAD

**Issue by jrgnicho** [ros-industrial-attic/jenkins_config#17]
The current build system compiles for ros groovy only.  It needs to be changed in order to allow selecting an alternate ros-distro such as hydro.

**Comment by shaun-edwards** [comment]
The rosinstall file format has ways of including the ROS version.  See the example at the bottom of this page: http://docs.ros.org/independent/api/rosinstall/html/rosinstall_file_format.html
