### ISSUE TITLE
groovy job doesn't seem to build pkgs other than industrial_core

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial-attic/jenkins_config#19]
I'm not sure whether this is intentional, but the [console output](http://raesjenkins.datasys.swri.edu/job/ros_industrial_groovy_dev/117/console) of the groovy-dev job seems to indicate that it only builds the `industrial_core` packages, even though it also checks out the `abb`, `fanuc`, `motoman` and `universal_robot` repositories.

This is probably due to the fact that the `build_catkin_workspace.sh` script runs catkin by invoking:

```
echo "============ Building catkin workspace ============"
catkin_make clean
catkin_make run_tests
```

Since none of the other packages declare any tests, they don't get built. IMO even just building those packages would provide valuable information, so could this be changed to just invoke `catkin_make`?

**Comment by shaun-edwards** [comment]
bump @jrgnicho
